name: generating a ascii image

on: push

jobs:
    image:
        runs-on: ubuntu-22.04
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: installing cowsay
          run: sudo apt-get install cowsay -y

        - name: execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a Dragon.....RAWR" >> dragon.txt
        
        - name: read the file
          run: cat dragon.txt

        - name: list files
          run: ls-ltra