name: generating a ascii image

on: push

jobs:
    image:
        runs-on: ubuntu-22.04
        steps:
        - name: checkout
          uses: actions/checkout@v4
          
        - name: list files
          run: ls -ltra

        - name: installing cowsay
          run: |
            chmod +x ascii-image.sh
            ./ascii-image.sh
