name: docker build, push and delpoy

on: push

env:
    DOCKER_USERNAME: charanreddy12
    DOCKER_IMAGE: testimage
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v4

          - name: docker login
            run: docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

          - name: docker build
            run: docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest .

          - name: docker push
            run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
