name: docker build, push and delpoy

on: push

env:
    DOCKER_USERNAME: charanreddy12
    DOCKER_IMAGE: testimage
jobs:
  # this is for testing the docker commands 
    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: checkout
    #         uses: actions/checkout@v4

    #       - name: docker login
    #         run: docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

    #       - name: docker build
    #         run: docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest .

    #       - name: docker push
    #         run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest


  # ===== this is by using the actions way to login and push the docker image =====

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login 
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:v1.0.0