name: script execution workflow

on:
    workflow_dispatch:

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: cheching out the code
          uses: actions/checkout@v4
        
        - name: listing the files 
          run: ls -ltr
        
        - name: executing the script
          run: |
            chmod +x ascii-image.sh
            ./ascii-image.sh
            
        
