name: first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: cheching out the code
          uses: actions/checkout@v4
        
        - name: welcome message
          run: |
            echo "welcome to github actions" 
            ls -ltra
            cat README.md
        

        # - name: listing the files 
        #   run: ls -ltr