name: matrix jobs
on: push
jobs:
    delpoy-matrix:
        strategy:
          fail-fast: false
          max-parallel: 3
          matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-22.04]
            images: [hello-world, alpine]
            exclude:
              - images: alpine
                os: windows-latest
            include:
              - images: amd64/alpine
                os: ubuntu-22.04
        runs-on: ${{ matrix.os }}
        steps:
            - name: Docker Version
              run: docker version

            - name: Run Docker Image on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
    