name: matrix jobs
on: push
jobs:
    delpoy-matrix:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            images: [hello-world, nginx]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Docker Version
              run: docker version

            - name: Run Docker Image on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
    