name: Parallel Jobs Example

on: 
    workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job 1
        run: echo "Running Job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Job 2
        run: echo "Running Job 2"
